name: Sample github action

on:
  workflow_call:
    secrets:
      repo_token:
        required: true
        description: Github token allowing access to the libraries and ghcr.

jobs:
  create_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: niaid/trellaction-workflow

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Create Github issues from Dependabot alerts
        env:
          REPO_TOKEN: ${{ secrets.repo_token }}
        run: python .github/scripts/create_issues.py