name: Sample github action

on:
  workflow_call:
    inputs:
      trello_list_name:
        required: true
        type: string
        description: Name of the list that should receive the Trello cards
    secrets:
      trello_board_id:
        required: true
        description: ID of the Trello board
      trello_api_key:
        required: true
        description: API key for the Trello board
      trello_api_secret:
        required: true
        description: API secret for the Trello board
      trello_token:
        required: true
        description: Token for the Trello board
      trello_token_secret:
        required: true
        description: Token secret for the Trello board
      repo_token:
        required: true
        description: Github token allowing access to the libraries and ghcr.

jobs:
  create_cards:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: niaid/trellaction-workflow
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py-trello
          pip install PyGithub
  
      - name: Create Trello cards from Github issues
        env:
          TRELLO_LIST_NAME: ${{ inputs.trello_list_name }}
          TRELLO_BOARD_ID: ${{ secrets.trello_board_id }}
          TRELLO_API_KEY: ${{ secrets.trello_api_key }}
          TRELLO_API_SECRET: ${{ secrets.trello_api_secret }}
          TRELLO_TOKEN: ${{ secrets.trello_token }}
          TRELLO_TOKEN_SECRET: ${{ secrets.trello_token_secret }}
          REPO_TOKEN: ${{ secrets.repo_token }}
        run: python .github/scripts/create_cards.py